project:
  type: website

website:
  title: "Albert Ji"
  navbar:
    right:
      - text: "Visulization"
        href: viz.qmd
      - icon: twitter
        href: https://x.com/peleusj
      - icon: github
        href: https://github.com/peleusj
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto



