project:
  type: website

website:
  title: "Albert Ji"
  navbar:
    pinned: true
    right:
      - text: "Visulization"
        href: viz.qmd
      - icon: twitter
        href: https://x.com/peleusj
      - icon: github
        href: https://github.com/peleusj

format:
  html:
    theme: 
      light: united
      dark: superhero
    css: styles.css
    # page-layout: full

execute:
  freeze: auto



